name: Cloudspark
options:
  minimumXcodeGenVersion: 2.43.0
  projectFormat: xcode16_0
  deploymentTarget:
    macOS: "26.0"
  defaultSourceDirectoryType: syncedFolder
fileGroups:
  - path: Support/cloudflare2
    type: folder
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.8.1
settings:
  base:
    SWIFT_VERSION: 6.0
    PRODUCT_BUNDLE_IDENTIFIER: com.zats.cloudspark2
    PRODUCT_NAME: Cloudspark
    MARKETING_VERSION: 1.15
    CURRENT_PROJECT_VERSION: 18
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: Support/cloudflare2/Info.plist
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
    CODE_SIGN_ENTITLEMENTS: Support/cloudflare2/Cloudflare2.entitlements
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5KE88HWMKJ
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  Cloudspark:
    type: application
    platform: macOS
    dependencies:
      - package: Sparkle
    sources:
      - path: Sources
        type: syncedFolder
        excludes:
          - Assets.xcassets
      - path: Sources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        AUTOMATION_APPLE_EVENTS: NO
        INFOPLIST_FILE: Support/cloudflare2/Info.plist
        CODE_SIGN_ENTITLEMENTS: Support/cloudflare2/Cloudflare2.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_RESOURCE_ACCESS_AUDIO_INPUT: NO
        ENABLE_RESOURCE_ACCESS_CALENDARS: NO
        ENABLE_RESOURCE_ACCESS_CAMERA: NO
        ENABLE_RESOURCE_ACCESS_CONTACTS: NO
        ENABLE_RESOURCE_ACCESS_LOCATION: NO
        ENABLE_RESOURCE_ACCESS_PHOTO_LIBRARY: NO
        RUNTIME_EXCEPTION_ALLOW_DYLD_ENVIRONMENT_VARIABLES: NO
        RUNTIME_EXCEPTION_ALLOW_JIT: NO
        RUNTIME_EXCEPTION_ALLOW_UNSIGNED_EXECUTABLE_MEMORY: NO
        RUNTIME_EXCEPTION_DEBUGGING_TOOL: NO
        RUNTIME_EXCEPTION_DISABLE_EXECUTABLE_PAGE_PROTECTION: NO
        RUNTIME_EXCEPTION_DISABLE_LIBRARY_VALIDATION: NO
schemes:
  Cloudspark:
    build:
      targets:
        Cloudspark: all
    run:
      config: Debug
    archive:
      config: Release
